service: sls-devagram-auth

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

plugins:
  - serverless-plugin-typescript

functions:
  signup:
    handler: functions/auth.register
    events:
    - http:
        path: register
        method: post
        cors: true